services:
  db:
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  wp:
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORPDRESS_DEBUG: 1
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./dist:/var/www/html/wp-content/themes/j2digital
volumes:
  db_data:
